In [1]:
import numpy as np

In [8]:
A=np.matrix([[8,2,3],[4,5,6],[7,8,9]])
A

matrix([[8, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
x=np.matrix([[1],[0],[0]])
x

matrix([[1],
        [0],
        [0]])

In [4]:
A*x

matrix([[1],
        [4],
        [7]])

In [9]:
A.getI()

matrix([[ 0.14285714, -0.28571429,  0.14285714],
        [-0.28571429, -2.42857143,  1.71428571],
        [ 0.14285714,  2.38095238, -1.52380952]])

In [10]:
A.getI()*A

matrix([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
        [ 2.22044605e-15,  1.00000000e+00,  3.10862447e-15],
        [-1.33226763e-15,  0.00000000e+00,  1.00000000e+00]])